export const fieldLabelsUI = {
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  phoneNumber: 'Phone Number',
  address: 'Street Address',
  city: 'City',
  zipCode: 'Zip Code',
  carMake: 'Car Make',
  carModel: 'Car Model',
  carColor: 'Car Color',
  carYear: 'Car Year',
  vin: 'Vin number',
  transmission: 'Transmission Type',
  pickupDate: 'Car Pickup Date',
  dropoffDate: 'Car Return Date',
  customerComments: 'Additional Comments',
};
